version: '3.8'

services:

  postgresql:
      image: postgres:14
      hostname: postgresql
      volumes:
        - pg_data_event_demo:/var/lib/postgresql/data
      environment:
        PGDATA: "/var/lib/postgresql/data"
        POSTGRES_DB: "conduktor-platform"
        POSTGRES_USER: "conduktor"
        POSTGRES_PASSWORD: "change_me"
        POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"

  conduktor-platform:
        image: conduktor/conduktor-platform:1.19.2
        container_name: conduktor-platform
        depends_on:
          - redpanda-0
        ports:
          - "8080:8080"
        volumes:
          - type: bind
            source: "./platform-config.yaml"
            target: /opt/conduktor/platform-config.yaml
            read_only: true
        environment:
          CDK_IN_CONF_FILE: /opt/conduktor/platform-config.yaml
          CDK_DATABASE_URL: postgresql://conduktor:change_me@postgresql:5432/conduktor-platform
          KAFKA_BOOTSTRAP_SERVER: redpanda-0:9092
          LICENSE_KEY: ${CDK_LICENSE}
          PROXY_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJvcmdJZCI6MSwiY2x1c3RlcklkIjoxLCJ1c2VybmFtZSI6InRlc3RAY29uZHVrdG9yLmlvIn0.Eb94MxCyesPeVdQmm0EDBGvhwcx8j-ST-mvmdAId_j0
          CDK_CLUSTERS_0_ID: "local-kafka"
          CDK_CLUSTERS_0_NAME: "local-kafka"
          CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "redpanda-0:9092"
          CDK_CLUSTERS_0_SCHEMAREGISTRY_URL: "http://redpanda-0:18081"
          CDK_CLUSTERS_0_COLOR: "#6A57C8"
          CDK_CLUSTERS_0_ICON: "kafka"
          CDK_CLUSTERS_1_ID: "cdk-gateway"
          CDK_CLUSTERS_1_NAME: "cdk-gateway"
          CDK_CLUSTERS_1_BOOTSTRAPSERVERS: "conduktor-gateway:6969"
          CDK_CLUSTERS_1_SCHEMAREGISTRY_URL: "http://redpanda-0:18081"
          CDK_CLUSTERS_1_KAFKAFLAVOR_URL: "http://conduktor-gateway:8888"
          CDK_CLUSTERS_1_KAFKAFLAVOR_USER: "admin"
          CDK_CLUSTERS_1_KAFKAFLAVOR_PASSWORD: "conduktor"
          CDK_CLUSTERS_1_KAFKAFLAVOR_VIRTUALCLUSTER: "passthrough"
          CDK_CLUSTERS_1_KAFKAFLAVOR_TYPE: "Gateway"
          CDK_CLUSTERS_1_COLOR: "#6A57C8"
          CDK_CLUSTERS_1_ICON: "dog"
          CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
          CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
          CDK_MONITORING_CALLBACK-URL: http://conduktor-platform:8080/monitoring/api/
          CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080
        healthcheck:
          test: curl -f http://localhost:8080/platform/api/modules/health/live || exit 1
          interval: 10s
          start_period: 10s
          timeout: 5s
          retries: 3

  conduktor-monitoring:
    image: conduktor/conduktor-platform-cortex:1.19.2
    environment:
      CDK_CONSOLE-URL: "http://conduktor-platform:8080"

  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with eachother internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.11
    container_name: redpanda-0
    volumes:
      - redpanda-0_event_demo:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
  
  conduktor-gateway:
    image: conduktor/conduktor-gateway:2.3.0
    hostname: conduktor-gateway
    container_name: conduktor-gateway
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda-0:9092
      GATEWAY_FEATURE_FLAGS_ANALYTICS: false
    ports:
      - "8888:8888"
    healthcheck:
      test: curl localhost:8888/health
      interval: 5s
      retries: 25
    depends_on:
      redpanda-0:
        condition: service_healthy
  conduktor-data-generator:
    image: conduktor/conduktor-data-generator:0.1
    container_name: conduktor-data-generator
    environment:
      KAFKA_BOOTSTRAP_SERVERS: conduktor-gateway:6969
      KAFKA_SCHEMA_REGISTRY_URL: http://redpanda-0:8081
      GATEWAY_ADMIN_API: http://conduktor-gateway:8888
    restart: on-failure
    depends_on:
      redpanda-0:
        condition: service_healthy
      conduktor-gateway:
        condition: service_healthy

volumes:
  pg_data_event_demo: {}
  redpanda-0_event_demo: {}
  conduktor_data_event_demo: {}